### PR TITLE
Add delta column

### PR DESCRIPTION
**Pull request by angussidney**
[As requested here](https://chat.stackexchange.com/transcript/message/39000046#39000046)

My attempt at an implementation. Untested, not sure whether it will work, but it's worth a try.

### CODE REVIEW

**Review by Undo1 — CHANGES_REQUESTED** [review]
This'll work on pageload, but won't update with the websocket. Would need to be JS changes for that. Probably not too hard to do.

**Comment by ArtOfCode-** [comment]
Add the following after line 29 in `app/assets/javascripts/vote_counts.coffee` (in the `$.each` loop):

```javascript
delta = $("#" + user_id + " .delta")
user_index = $("tr").index($("#" + user_id))
if user_index == 0
  next_score = parseInt($($("tr")[1]).find(".delta").text(), 10)
  continue if isNaN(next_score)
  delta.text 'Leading by ' + (parseInt(delta.text(), 10) - next_score)
else
  prev_score = parseInt($($("tr")[user_index - 1]).find(".delta").text(), 10)
  continue if isNaN(prev_score)
  delta.text prev_score - parseInt(delta.text(), 10)
```

**Review by Undo1 — APPROVED** [review]

**Comment by Undo1** [comment]
Something about the JS here isn't working; the deltas aren't updating. See screenshot:

screen shot 2017-07-26 at 7 59 13 pm

Delta there should be higher. Rolled back production to 7cc0c5f52ec7c16d34df1713e575839f76c1aaab until I (or anyone) gets time to figure it out.

**Comment by ArtOfCode-** [comment]
This is what I get for doing 5-minute JS

**Pull request merged**
